root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("B","Tight_PtEtaBins","Efficiency20_miniTight_Tight_abseta/DATA_dataidB/TnP_MC_NUM_TightIso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_miniTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_TightIso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("C","Tight_PtEtaBins","Efficiency20_miniTight_Tight_abseta/DATA_dataidC/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_miniTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("D","Tight_PtEtaBins","Efficiency20_miniTight_Tight_abseta/DATA_dataidD/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_miniTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("E","Tight_PtEtaBins","Efficiency20_miniTight_Tight_abseta/DATA_dataidE/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_miniTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("F","Tight_PtEtaBins","Efficiency20_miniTight_Tight_abseta/DATA_dataidF/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_miniTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_TightRelIso_DEN_TightIDandIPCut_PAR_pt_eta.root")'

root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("B","Loose_PtEtaBins","Efficiency20_miniLoose_Loose_abseta/DATA_dataidB/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_miniLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("C","Loose_PtEtaBins","Efficiency20_miniLoose_Loose_abseta/DATA_dataidC/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_miniLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("D","Loose_PtEtaBins","Efficiency20_miniLoose_Loose_abseta/DATA_dataidD/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_miniLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("E","Loose_PtEtaBins","Efficiency20_miniLoose_Loose_abseta/DATA_dataidE/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_miniLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("F","Loose_PtEtaBins","Efficiency20_miniLoose_Loose_abseta/DATA_dataidF/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_miniLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_LooseRelIso_DEN_LooseID_PAR_pt_eta.root")'


root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("B","Tight_PtEtaBins","Efficiency20_PFTight_Tight_abseta/DATA_dataidB/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_PFTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("C","Tight_PtEtaBins","Efficiency20_PFTight_Tight_abseta/DATA_dataidC/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_PFTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("D","Tight_PtEtaBins","Efficiency20_PFTight_Tight_abseta/DATA_dataidD/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_PFTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("E","Tight_PtEtaBins","Efficiency20_PFTight_Tight_abseta/DATA_dataidE/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_PFTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("F","Tight_PtEtaBins","Efficiency20_PFTight_Tight_abseta/DATA_dataidF/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root", "Efficiency20_PFTight_Tight_abseta/MC_mc2017/TnP_MC_NUM_tightPFiso_DEN_TightIDandIPCut_PAR_pt_eta.root")'

root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("B","Loose_PtEtaBins","Efficiency20_PFLoose_Loose_abseta/DATA_dataidB/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_PFLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("C","Loose_PtEtaBins","Efficiency20_PFLoose_Loose_abseta/DATA_dataidC/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_PFLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("D","Loose_PtEtaBins","Efficiency20_PFLoose_Loose_abseta/DATA_dataidD/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_PFLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("E","Loose_PtEtaBins","Efficiency20_PFLoose_Loose_abseta/DATA_dataidE/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_PFLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root")'
root -b -q -l 'plotsAndSFsExtractor/extractPlotsAndComputeTheSFs.C("F","Loose_PtEtaBins","Efficiency20_PFLoose_Loose_abseta/DATA_dataidF/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root", "Efficiency20_PFLoose_Loose_abseta/MC_mc2017/TnP_MC_NUM_loosePFiso_DEN_LooseID_PAR_pt_eta.root")'
