sleep 5
echo 'RunB'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2017/94X/RunB/TnPTree_17Nov2017_SingleMuon_Run2017Bv1_Full_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunB.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerB.log 2>&1 &

sleep 5
echo 'RunC'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2017/94X/RunC/TnPTree_17Nov2017_SingleMuon_Run2017Cv1_Full_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunC.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" </dev/null > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerC.log 2>&1 &

sleep 5
echo 'RunD'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2017/94X/RunD/TnPTree_17Nov2017_SingleMuon_Run2017Dv1_Full_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunD.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" </dev/null > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerD.log 2>&1 &

sleep 5
echo 'RunE'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2017/94X/RunE/TnPTree_17Nov2017_SingleMuon_Run2017Ev1_Full_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunE.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" </dev/null > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerE.log 2>&1 &

sleep 5
echo 'RunF'
nohup TnPUtils/skimTree /eos/cms/store/group/phys_muon/TagAndProbe/Run2017/94X/RunF/TnPTree_17Nov2017_SingleMuon_Run2017Fv1_Full_GoldenJSON.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_RunF.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" </dev/null > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerF.log 2>&1 &

sleep 5
echo 'DYTree'
nohup TnPUtils/skimTree /eos/user/w/wiwong/TagAndProbe/add_PUweight/TnPTree_DY2017_weighted.root /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmed_20_DY.root -r "all" -k "pt abseta dB dzPV eta mass pair_newTuneP_mass pair_newTuneP_probe_pt pair_probeMultiplicity pair_deltaR run IsoMu24 IsoTkMu24 Mu50 fixedGridRhoFastjetCentralNeutral miniIsoCharged miniIsoNeutrals miniIsoPhotons combRelIsoPF04dBeta CutBasedIdTight CutBasedIdMedium CutBasedIdLoose tag_nVertices weight" -c "((pt > 20 || pair_newTuneP_probe_pt > 20) && mass > 69.5 && mass < 130.1 && tag_combRelIsoPF04dBeta < 0.2 && tag_combRelIsoPF04dBeta > -0.5 && tag_pt > 30 && tag_IsoMu27 == 1 && abseta < 2.401 && pair_probeMultiplicity == 1)" </dev/null > /eos/user/w/wiwong/TagAndProbe/skimtree_out/skimmerDY.log 2>&1 &
